package com.linghualive.flamekit.core.theme

import androidx.compose.ui.graphics.Color

val Seed = Color(0xFF5B6ABF)

// Light scheme — indigo/blue palette
val md_theme_light_primary = Color(0xFF4A5899)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDEE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF0F1B5E)
val md_theme_light_secondary = Color(0xFF5B5D72)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE0E1F9)
val md_theme_light_onSecondaryContainer = Color(0xFF181A2C)
val md_theme_light_tertiary = Color(0xFF77536D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD7F1)
val md_theme_light_onTertiaryContainer = Color(0xFF2D1228)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE3E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_outline = Color(0xFF767680)

// Dark scheme — indigo/blue palette
val md_theme_dark_primary = Color(0xFFB8C4FF)
val md_theme_dark_onPrimary = Color(0xFF223070)
val md_theme_dark_primaryContainer = Color(0xFF394780)
val md_theme_dark_onPrimaryContainer = Color(0xFFDEE1FF)
val md_theme_dark_secondary = Color(0xFFC4C5DD)
val md_theme_dark_onSecondary = Color(0xFF2D2F42)
val md_theme_dark_secondaryContainer = Color(0xFF434559)
val md_theme_dark_onSecondaryContainer = Color(0xFFE0E1F9)
val md_theme_dark_tertiary = Color(0xFFE6BAD7)
val md_theme_dark_onTertiary = Color(0xFF44263D)
val md_theme_dark_tertiaryContainer = Color(0xFF5D3C55)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD7F1)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE4E1E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE4E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF46464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C5D0)
val md_theme_dark_outline = Color(0xFF90909A)
